version: '3.8'

services:
  # CAJA 1: TU APLICACI√ìN ‚òï
  api-app:
    build: .
    ports:
      - "8080:8080" # Abre la ventana 8080
    environment:
      # AQU√ç EST√Å EL TRUCO: Le decimos que la BD no est√° en 'localhost',
      # sino en la otra caja llamada 'mi-mysql-docker'
      SPRING_DATASOURCE_URL: jdbc:mysql://mi-mysql-docker:3306/primer_api_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mi-mysql-docker # Espera a que la BD arranque antes de intentarlo

  # CAJA 2: BASE DE DATOS üóÑÔ∏è
  mi-mysql-docker:
    image: mysql:8.0 # Descarga un MySQL oficial
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: primer_api_db
    ports:
      - "3307:3306" # (Opcional) La ponemos en el 3307 para que no choque con tu MySQL de Windows